# Generated by Django 5.1.2 on 2024-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user_alter_book_isbn_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=50),
        ),
    ]
